# Default values for spark.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

Spark:
  Path: "/usr/share/spark"

Master:
  Name: master
  Image: "dos65/mist-k8s"
  ImageTag: "1.0.0"
  Replicas: 1
  Component: "spark-master"
  Cpu: "100m"
  Memory: "512Mi"
  ServicePort: 7077
  ContainerPort: 7077
  ServiceHttpPort: 8080
  ContainerHttpPort: 8080
  ServiceHttpApiPort: 6066
  ContainerHttpApiPort: 6066
  ServiceType: LoadBalancer

Worker:
  Name: worker
  Image: "dos65/mist-k8s"
  ImageTag: "1.0.0"
  Replicas: 2
  Component: "spark-worker"
  Cpu: "100m"
  Memory: "512Mi"
  ContainerPort: 8081
  # Set Worker JVM memory. Default 1g
  # DaemonMemory: 1g
  # Set how much total memory workers have to give executors
  # ExecutorMemory: 1g
  CpuTargetPercentage: 50

Mist:
  Name: "mist"
  Image: "dos65/mist-k8s"
  ImageTag: "1.0.0"
  Replicas: 1
  Component: "mist-server"
  Cpu: "100m"
  Memory: "1G"
  ServiceHttpPort: 2004
  ContainerHttpPort: 2004
  ServiceAkkaPort: 2551
  ContainerAkkaPort: 2551
  ServiceLogsPort: 2005
  ContainerLogsPort: 2005
  ServiceType: LoadBalancer
