FROM anapsix/alpine-java:8

RUN apk update
RUN apk add python curl coreutils jq

RUN curl -o /usr/share/spark.tar.gz https://archive.apache.org/dist/spark/spark-2.3.0/spark-2.3.0-bin-hadoop2.7.tgz \
   && cd /usr/share \
   && tar xvfz spark.tar.gz \
   && rm -f /usr/share/spark.tar.gz \
   && mv spark-2.3.0-bin-hadoop2.7 spark
  
ENV SPARK_HOME /usr/share/spark

RUN curl -o /usr/share/mist.tar.gz http://repo.hydrosphere.io/hydrosphere/static/mist-1.0.0-RC16.tar.gz \
    && cd /usr/share \
    && tar xvfz mist.tar.gz \
    && rm -f /usr/share/mist.tar.gz \
    && mv mist-1.0.0-RC16 mist

COPY default.conf /usr/share/mist/default.conf

CMD /usr/share/mist/bin/mist-master start --debug true

EXPOSE 2004
